In [1]:
import numpy as np

In [7]:
X=[[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-0.8]]
np.random.seed(0)
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
# weights of nn represented in a class, n_inputs,n_neurons give the matrix a shape.
        self.weights = 0.10*np.random.randn(n_inputs,n_neurons)
# assign init value of 0 to biases.
        self.biases = np.zeros((1,n_neurons))
    def forward(self,outputs):
# to get the output we use np.dot() method to do the matrix multiplication.
        self.outputs = np.dot(self.inputs,self.weights)+ self.biases
        
        
#
Layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,)

[[ 0.17640523  0.04001572  0.0978738 ]
 [ 0.22408932  0.1867558  -0.09772779]
 [ 0.09500884 -0.01513572 -0.01032189]
 [ 0.04105985  0.01440436  0.14542735]]


In [ ]:
weights=[[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
weights2=[[0.1,-0.14,0.5],[0.5,-0.12,-0.33],[-0.44,0.73,-0.13]]
biases = [2,3,0.5]
biases2 =[-1,2,-0.5]


layer1_outputs = np.dot(inputs,np.array(weights).T)+biases
layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) + biases2

#print(output)
print(layer2_outputs)


In [17]:
nombregata="alegria"
print(nombregata)

alegria
