<a href="https://colab.research.google.com/github/123-code/Deep-Learning-from-scratch/blob/main/Full_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
!pip install nnfs


In [2]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()


class Layer:
  def __init__(self,inputs,nneurons):
    self.weights = 0.10 * np.random.randn(inputs,nneurons)
    self.bias = np.zeros((1,nneurons))

  def forward(self,inputs):
      self.output = np.dot(inputs,self.weights) + self.bias
     


class RELU_A:
  def forward(self,inputs):

    self.output = np.maximum(0,inputs)


class Softmax:
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output = probabilities


X,y = spiral_data(samples=100,classes=3)
dense1 = Layer(2,3)
activation1 = RELU_A()

dense2 = Layer(3,3)
activation2 = Softmax()
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
