<a href="https://colab.research.google.com/github/123-code/Neural-Networks-from-scratch/blob/main/Full_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
!pip install nnfs


In [ ]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()


class Layer:
  def __init__(self,inputs,nneurons):
    self.weights = 0.10 * np.random.randn(inputs,nneurons)
    self.bias = np.zeros((1,nneurons))

  def forward(self,inputs):
      self.output = np.dot(inputs,self.weights) + self.bias
     


class RELU_A:
  def forward(self,inputs):

    self.output = np.maximum(0,inputs)


class Softmax:
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output = probabilities

class Loss:
  # output from the model and target values.
  def calculate(self,output,y):
    sample_losses = self.forward(output,y)
    data_loss = np.mean(sample_losses)
    return data_loss

class categoricalcrossentropy(Loss):
  def forward(self,y_pred,y_true):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred,1e-7,1-1e-7)

    if len(y_true.shape)==1:
      correct_conf = y_pred_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_conf = np.sum(y_pred_clipped*y_true,axis=1)
    
    negative_log_likelihoods = np.log(correct_conf)
    return negative_log_likelihoods



X,y = spiral_data(samples=100,classes=3)
dense1 = Layer(2,3)
activation1 = RELU_A()

dense2 = Layer(3,3)
activation2 = Softmax()
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])
Loss = categoricalcrossentropy()
loss = Loss.calculate(activation2.output,y)
print("Loss:",loss)

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
Loss: -1.098445


Neural Network 2


In [ ]:
data = [[2,5,8,9],[6,8,3,1],[7,9,4,5],[6,4,2,1]]
#np.random.seed(0)
# setting initial weights and biases. 
class Layer1:
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))

  def Forward_pass(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases
# Values printed in output are a matrix of each neurons dot product result. 

class RELU:
  def forward(self,inputs):

    self.output = np.maximum(0,inputs)
  

L1 = Layer1(4,3)
L1.Forward_pass(data)
print(L1.output)
activation_1 = RELU()
activation_1.forward(L1.output)
print(activation_1.output[:5])


[[0.48369895 1.06012667 2.91633185]
 [1.78269892 0.50147318 3.0249836 ]
 [1.97679322 0.88927948 3.86635385]
 [1.4470814  0.76571782 2.16623242]]
[[0.48369895 1.06012667 2.91633185]
 [1.78269892 0.50147318 3.0249836 ]
 [1.97679322 0.88927948 3.86635385]
 [1.4470814  0.76571782 2.16623242]]


In [ ]:
softmax_outputs = np.array([0.7,0.1,0.2],
                           [0.1,0.5,0.4],
                           [0.02,0.9,0.08])

class_targets = [0,1,1]
print(softmax_outputs[0,1,2],class_targets)

Full NN 2


In [ ]:
def sigmoid(x):
  sigmoid = (1/(1+np.exp(-x)))
  return sigmoid

# randomly initializing weights.
def init_W(inp_size,hidd_size):
  weights = {}
  weights['W1'] = np.random.randn(inp_size,hidd_size)
  weights['B1'] = np.random.randn(1,hidd_size)
  weights['W2'] = np.random.randn(inp_size,hidd_size)
  weights['B2'] = np.random.randn(1,hidd_size)
  return weights

def Forward_Loss(X,y,weights):
  W_sum = np.dot(X,weights['W1'])
  output = W_sum + weights['B1']
  Activated1 = np.dot(W_sum,output)

  W_sum2 = np.dot(Activated1,weights['W2'])
  output2 = W_sum + weights['B1']

  loss = np.mean((y-output2)**2)

# saving forward pass data.
  forward_info = {}
  forward_info['W_sum1'] = W_sum
  forward_info['output1'] = output
  forward_info['Sigm1'] = Activated1
  forward_info['Wsum2'] = W_sum2
  forward_info['output2'] = output2
  forward_info['X'] = X
  forward_info['y'] = y

  return forward_info,loss

def Calc_gradients(forward_info,weights):
  '''
  #Compute the partial derivatives of the loss with respect to each of the parameters in the neural network.
  this is done to see how the error changes with respect to changes in any part of the network.
  '''
  dldp = -(forward_info['y'] - forward_info['output2'])
  dpdw2 = np.ones_like(forward_info['Wsum2'])
  dlw2 = dldp * dpdw2
  dpdb2 = np.ones_like(weights['B2'])
  dldb2 = (dpdb2 * dldp).sum(axis=0)
  dp2dW2 = np.transpose(forward_info['Sigm1'], (1, 0))
  dLdW2 = np.dot(dM2dW2, dldp)
  dpdsigm = np.transpose(weights['W2'], (1, 0)) 
  dldsigm = np.dot(dpdsigm,dpdsigm)
  dSigm1dO1 = sigmoid(forward_info['output1']) * (1- sigmoid(forward_info['output1']))
  dldO1 = dldsigm * dlSigm
  dO1dB1 = np.ones_like(weights['B1'])
  dN1dM1 = np.ones_like(forward_info['W_sum1'])  
  dLdB1 = (dLdO1 * dO1b1).sum(axis=0)
  dWs1dW1 = np.transpose(forward_info['X'], (1, 0)) 
  dLdW = np.dot(dws1dw1, dLdB1)


  Loss_Gradients = {}
  Loss_Gradients['W2'] = dLdW2
  Loss_Gradients['B1'] = dLdB1.sum(axis=0)
  Loss_Gradients['W1'] = dLdW
  Loss_Gradients['B2'] = dldb2

def predict(X,weights):
  L1 = np.dot(X,weights['W1'])
  output1 = L1 + weights['B1']

  LR1 = sigmoid(output1)

  L2 = np.dot(LR1,weights['W2'])

# Final prediction.
  LR2 = L2 + weights['B2']
'''
  loss = (np.mean(forward_info['y'] - LR2))**2
'''
  return LR2

predictions = predict(X,weights)

 







In [ ]:
from numpy import ndarray

def assert_same_shape(arr1,arr2):
  assert arr1.shape() == arr2.shape()
  return None

class Operations(object):
  def __init__ (self):
    pass

  def forward(self,input:ndarray):
    self.input = input
    self.output = self.output()

    return self.output

  def backward(self,output_grad:ndarray):
    assert_same_shape(self.output,output_grad)

    self.input_grad = self.input_grad(output_grad)

    assert_same_shape(self.input_grad,self.output_grad)

    return self.input_grad

  def output(self):

    raise NotImplementedError()

  def input_grad(self,output_grad):
    raise NotImplementedError()


class ParameterOperation(Operations):
  def __init__ (self,param):
    super().__init__()
    self.param=param

  def backward(self,output_grad):
    assert_same_shape(self.output,output_grad)

    self.input_grad = self.input_grad(output_grad)
    self.param_grad = self.param_grad(output_grad)

    assert_same_shape(self.input_grad,self.input)
    assert_same_shape(self.param,self.param_grad)

  def param_grad(self,output_grad): 
    raise NotImplementedError()


    
    

   





In [ ]:
class WeightMultiply(ParameterOperation):
  def __init__(self,W):
    super().__init__(W)


  def _output(self):
    return(np.dot(self.input_,self.param))


  def _input_grad(self,output_grad):
    return(np.dot(output_grad,np.transpose(self.param,(1,0))))

  def _param_grad(self,output_grad):
    return(np.dot(np.transpose(self.input_,(1,0))),output_grad)
     

class BiasAddition(ParameterOperation):
  def __init__ (self,B):
    assert B.shspe[0] == 1

    super().__init__()

  def _output(self):
    return self.input_ + self.param

  def _input_grad(self,output_grad):
    return np.ones_like(self.input_) * output_grad

  def param_grad(self,output_grad):
    param_grad = np.ones_like(self.input_)*output_grad
    return(np.sum(param_grad,axis=0).reshape(1,param_grad.shape[1]))

  

class Sigmoid(Operations):
  def __init__(self):
    super().__init__()

  def _output(self):
    return(1.0/1.0+np.exp(-1.0*self.input_))

  def _input_grad(self,output_grad):
    sigmoid_backward = self.output*(1.0-self.output)
    input_grad = sigmoid_backward*output_grad
    return input_grad


class Layer(object):
  def __init__ (self,neurons):

    self.neurons = neurons
    self.first = True
    self.params = []
    self.param_grads = []
    self.operations = []

  def setup_layer(self,num):
    raise NotImplementedError()


  def forward(self,input_):
    if self.first:
      self.setup_layer(input_)
      self.first = False

    self.input_ = input_

    for operation in self.operations:
      input_ = operation.forward(input_)

    self.output = input_

    return self.output


  def backward(self,output_grad):
    assert_same_shape(self.output,output_grad)

    for operation in reversed(self.operations):
      output_grad = operation.backward(output_grad)

    input_grad = output_grad

    self.param_grads()

    return input_grad

def param_grads(self):
  pass





  




In [ ]:
import numpy as np
inputs = np.array([2,8,7,5,4,3])
weights = np.random.randn(6,1)*0.10
biases = np.ones_like(inputs)
expected = np.array([3,5,7,8,2,1])
lr = 0.1


class NN:
  def __init__ (self,inputs,weights,biases,expected,lr):
    self.inputs = inputs
    self.weights = weights
    self.biases = biases
    self.expected = expected
    self.lr = lr

  def forward(self,inputs,weights):
    for i in range(10):

      output = np.dot(self.inputs,self.weights)
      loss = ((expected - output)**2).mean()
      n = self.inputs.shape[0]
      gradient = 2*(expected - output)/n
      self.weights = self.weights - (self.lr * gradient)

      print(f'Error:{loss} --- Prediction:{output}')
    

      


 
    

n1 = NN(inputs,weights,biases,expected,lr) 
pred = n1.forward(inputs,weights)
print(pred)