<a href="https://colab.research.google.com/github/123-code/Deep-Learning-from-scratch/blob/main/Full_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
!pip install nnfs


In [4]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()


class Layer:
  def __init__(self,inputs,nneurons):
    self.weights = 0.10 * np.random.randn(inputs,nneurons)
    self.bias = np.zeros((1,nneurons))

  def forward(self,inputs):
      self.output = np.dot(inputs,self.weights) + self.bias
     


class RELU_A:
  def forward(self,inputs):

    self.output = np.maximum(0,inputs)


class Softmax:
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output = probabilities

class Loss:
  # output from the model and target values.
  def calculate(self,output,y):
    sample_losses = self.forward(output,y)
    data_loss = np.mean(sample_losses)
    return data_loss

class categoricalcrossentropy(Loss):
  def forward(self,y_pred,y_true):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred,1e-7,1-1e-7)

    if len(y_true.shape)==1:
      correct_conf = y_pred_clipped[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_conf = np.sum(y_pred_clipped*y_true,axis=1)
    
    negative_log_likelihoods = np.log(correct_conf)
    return negative_log_likelihoods



X,y = spiral_data(samples=100,classes=3)
dense1 = Layer(2,3)
activation1 = RELU_A()

dense2 = Layer(3,3)
activation2 = Softmax()
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])
Loss = categoricalcrossentropy()
loss = Loss.calculate(activation2.output,y)
print("Loss:",loss)

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
Loss: -1.098445


Neural Network 2


In [ ]:
data = [[2,5,8,9],[6,8,3,1],[7,9,4,5],[6,4,2,1]]
#np.random.seed(0)
# setting initial weights and biases. 
class Layer1:
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))

  def Forward_pass(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.biases
# Values printed in output are a matrix of each neurons dot product result. 

class RELU:
  def forward(self,inputs):

    self.output = np.maximum(0,inputs)
  

L1 = Layer1(4,3)
L1.Forward_pass(data)
print(L1.output)
activation_1 = RELU()
activation_1.forward(L1.output)
print(activation_1.output[:5])


[[0.48369895 1.06012667 2.91633185]
 [1.78269892 0.50147318 3.0249836 ]
 [1.97679322 0.88927948 3.86635385]
 [1.4470814  0.76571782 2.16623242]]
[[0.48369895 1.06012667 2.91633185]
 [1.78269892 0.50147318 3.0249836 ]
 [1.97679322 0.88927948 3.86635385]
 [1.4470814  0.76571782 2.16623242]]


In [2]:
softmax_outputs = np.array([0.7,0.1,0.2],
                           [0.1,0.5,0.4],
                           [0.02,0.9,0.08])

class_targets = [0,1,1]
print(softmax_outputs[0,1,2],class_targets)

TypeError: ignored