<a href="https://colab.research.google.com/github/123-code/Neural-Networks-from-scratch/blob/main/MyNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np


X =    [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

y = np.ones((3,3))


class Layer:
  def __init__ (self,inputs,nneurons):
    self.weights = 0.10 * np.random.randn(inputs,nneurons)
    self.bias = np.zeros((1,nneurons))

  def forward(self,inputs):
    
    output = np.dot(inputs,self.weights) + self.bias
    return output

class RELU:
  def __init__(self,inputs):
    self.output = np.maximum(0,inputs)
  def calculate(self):
    return self.output

class Loss:
  def __init__(self,output,y):
    self.loss = (output - y)**2
    self.mse = np.mean(self.loss)
  def calculate(self):

    return self.mse

class Gradients:
  def __init__(self,inputs,y):
    n = inputs.shape[0]
    self.output = 2*(inputs-y)/n
  def calculate(self):
    return self.output




layer1 = Layer(4,3)
pred = layer1.forward(X)
print(f'Predicted:  {pred}\n')

activation1 = RELU(pred)
activation1 = activation1.calculate()

print(f'Actual:{y}\n')


print(f'Activation:{activation1}\n')

loss = Loss(y,activation1)
loss = loss.calculate()
print(f'Loss:{loss}\n')


gradients = Gradients(pred,y)
gradients = gradients.calculate()
print(f'Gradients:{gradients}')







Predicted:  [[-0.24596451 -0.44296989  0.10187329]
 [-0.38611024 -0.37879149 -0.17926033]
 [ 0.10608344 -0.6721945   0.44633901]]

Actual:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Activation:[[0.         0.         0.10187329]
 [0.         0.         0.        ]
 [0.10608344 0.         0.44633901]]

Loss:0.8791398766872176

Gradients:[[-0.83064301 -0.96197992 -0.59875114]
 [-0.92407349 -0.91919433 -0.78617355]
 [-0.59594438 -1.11479633 -0.36910732]]
