<a href="https://colab.research.google.com/github/123-code/Deep-Learning-from-scratch/blob/main/Softmax_Activation_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import math 



layer_outputs = [4.8,1.21,2.385]

E = math.e

exp_values = []

for output in layer_outputs:
  exp_values.append(E**output)

print(exp_values)

norm_base = sum(exp_values)
norm_values = []

for i in exp_values:
  norm_values.append(i / norm_base)

print(norm_values)
print(sum(norm_values))

[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


Numpy implementation

In [3]:
import numpy as np
layer_outputs = [4.8,1.21,2.385]

E = math.e

exp_values = np.exp(layer_outputs)
print(exp_values)

norm_values = exp_values/np.sum(exp_values)
print(norm_values)
print(sum(norm_values))

[121.51041752   3.35348465  10.85906266]
[0.89528266 0.02470831 0.08000903]
0.9999999999999999


Softmax With batches

In [13]:
layer_outputs = [[4.8,1.21,2.385],
                 [8.9,-1.81,0.2],
                 [1.41,1.051,0.026]]

exp = np.exp(layer_outputs)  


# we use the axis=1 to get a sum of the rows, not the columns 
# keepdims to change the matrix orientation.

normalized = exp / np.sum(layer_outputs,axis=1,keepdims=True)


print(normalized)


[[1.44741415e+01 3.99462138e-01 1.29351551e+00]
 [1.00575769e+03 2.24491271e-02 1.67544960e-01]
 [1.64694628e+00 1.15018504e+00 4.12682327e-01]]
